### PR TITLE
Fix C++ Bazel build

### PR DESCRIPTION
**Pull request by lidizheng**
Test run: [sponge/bcffeaae-6888-4181-86ad-8f7b65d3d9df](http://sponge/bcffeaae-6888-4181-86ad-8f7b65d3d9df)

gRPC Core's essential dependency `upb` has checked-in code that requires Bazel >3.4 (see [code](https://github.com/protocolbuffers/upb/blob/master/bazel/upb_proto_library.bzl#L369)). So, this PR bumped the Bazel version to align with gRPC main repo.

Also, it fixed other Bazel dependency issues. Let's see if tests are happy.

---
This change is [Reviewable](https://reviewable.io/reviews/googlecloudplatform/traffic-director-grpc-examples/23)

### CODE REVIEW

**Comment by lidizheng** [comment]
C++ build continue to fail:

```
external/com_github_grpc_grpc/src/core/lib/debug/stats.cc: In function 'std::string grpc_stats_data_as_json(const grpc_stats_data*)':
external/com_github_grpc_grpc/src/core/lib/debug/stats.cc:153:75: error: no matching function for call to 'StrFormat(const char [10], const char*&, const gpr_atm&)'
         "\"%s\": %" PRIdPTR, grpc_stats_counter_name[i], data->counters[i]));
                                                                           ^
external/com_github_grpc_grpc/src/core/lib/debug/stats.cc:153:75: note: candidate is:
In file included from external/com_github_grpc_grpc/src/core/lib/debug/stats.cc:28:0:
external/com_google_absl/absl/strings/str_format.h:338:34: note: template<class ... Args> std::string absl::lts_2020_09_23::StrFormat(absl::lts_2020_09_23::FormatSpec<Args ...>&, const Args& ...)
 ABSL_MUST_USE_RESULT std::string StrFormat(const FormatSpec<Args...>& format,
                                  ^
external/com_google_absl/absl/strings/str_format.h:338:34: note:   template argument deduction/substitution failed:
external/com_github_grpc_grpc/src/core/lib/debug/stats.cc:153:75: note:   mismatched types 'absl::lts_2020_09_23::FormatSpec<Args ...>' and 'const char [10]'
         "\"%s\": %" PRIdPTR, grpc_stats_counter_name[i], data->counters[i]));
                                                                           ^
external/com_github_grpc_grpc/src/core/lib/debug/stats.cc:156:78: error: no matching function for call to 'StrFormat(const char [8], const char*&)'
     parts.push_back(absl::StrFormat("\"%s\": [", grpc_stats_histogram_name[i]));
                                                                              ^
external/com_github_grpc_grpc/src/core/lib/debug/stats.cc:156:78: note: candidate is:
In file included from external/com_github_grpc_grpc/src/core/lib/debug/stats.cc:28:0:
external/com_google_absl/absl/strings/str_format.h:338:34: note: template<class ... Args> std::string absl::lts_2020_09_23::StrFormat(absl::lts_2020_09_23::FormatSpec<Args ...>&, const Args& ...)
 ABSL_MUST_USE_RESULT std::string StrFormat(const FormatSpec<Args...>& format,
                                  ^
external/com_google_absl/absl/strings/str_format.h:338:34: note:   template argument deduction/substitution failed:
external/com_github_grpc_grpc/src/core/lib/debug/stats.cc:156:78: note:   mismatched types 'absl::lts_2020_09_23::FormatSpec<Args ...>' and 'const char [8]'
     parts.push_back(absl::StrFormat("\"%s\": [", grpc_stats_histogram_name[i]));
                                                                              ^
external/com_github_grpc_grpc/src/core/lib/debug/stats.cc:160:74: error: no matching function for call to 'StrFormat(const char [6], const char*, const gpr_atm&)'
                           data->histograms[grpc_stats_histo_start[i] + j]));
                                                                          ^
external/com_github_grpc_grpc/src/core/lib/debug/stats.cc:160:74: note: candidate is:
In file included from external/com_github_grpc_grpc/src/core/lib/debug/stats.cc:28:0:
external/com_google_absl/absl/strings/str_format.h:338:34: note: template<class ... Args> std::string absl::lts_2020_09_23::StrFormat(absl::lts_2020_09_23::FormatSpec<Args ...>&, const Args& ...)
 ABSL_MUST_USE_RESULT std::string StrFormat(const FormatSpec<Args...>& format,
                                  ^
external/com_google_absl/absl/strings/str_format.h:338:34: note:   template argument deduction/substitution failed:
external/com_github_grpc_grpc/src/core/lib/debug/stats.cc:160:74: note:   mismatched types 'absl::lts_2020_09_23::FormatSpec<Args ...>' and 'const char [6]'
                           data->histograms[grpc_stats_histo_start[i] + j]));
                                                                          ^
external/com_github_grpc_grpc/src/core/lib/debug/stats.cc:163:73: error: no matching function for call to 'StrFormat(const char [15], const char*&)'
         absl::StrFormat("], \"%s_bkt\": [", grpc_stats_histogram_name[i]));
                                                                         ^
external/com_github_grpc_grpc/src/core/lib/debug/stats.cc:163:73: note: candidate is:
In file included from external/com_github_grpc_grpc/src/core/lib/debug/stats.cc:28:0:
external/com_google_absl/absl/strings/str_format.h:338:34: note: template<class ... Args> std::string absl::lts_2020_09_23::StrFormat(absl::lts_2020_09_23::FormatSpec<Args ...>&, const Args& ...)
 ABSL_MUST_USE_RESULT std::string StrFormat(const FormatSpec<Args...>& format,
                                  ^
external/com_google_absl/absl/strings/str_format.h:338:34: note:   template argument deduction/substitution failed:
external/com_github_grpc_grpc/src/core/lib/debug/stats.cc:163:73: note:   mismatched types 'absl::lts_2020_09_23::FormatSpec<Args ...>' and 'const char [15]'
         absl::StrFormat("], \"%s_bkt\": [", grpc_stats_histogram_name[i]));
                                                                         ^
external/com_github_grpc_grpc/src/core/lib/debug/stats.cc:166:78: error: no matching function for call to 'StrFormat(const char [5], const char*, const int&)'
           "%s%d", j == 0 ? "" : ",", grpc_stats_histo_bucket_boundaries[i][j]));
                                                                              ^
external/com_github_grpc_grpc/src/core/lib/debug/stats.cc:166:78: note: candidate is:
In file included from external/com_github_grpc_grpc/src/core/lib/debug/stats.cc:28:0:
external/com_google_absl/absl/strings/str_format.h:338:34: note: template<class ... Args> std::string absl::lts_2020_09_23::StrFormat(absl::lts_2020_09_23::FormatSpec<Args ...>&, const Args& ...)
 ABSL_MUST_USE_RESULT std::string StrFormat(const FormatSpec<Args...>& format,
                                  ^
external/com_google_absl/absl/strings/str_format.h:338:34: note:   template argument deduction/substitution failed:
external/com_github_grpc_grpc/src/core/lib/debug/stats.cc:166:78: note:   mismatched types 'absl::lts_2020_09_23::FormatSpec<Args ...>' and 'const char [5]'
           "%s%d", j == 0 ? "" : ",", grpc_stats_histo_bucket_boundaries[i][j]));
```

**Comment by lidizheng** [comment]
[sponge/ae423ad3-4135-46dd-b551-935a6caa974c](http://sponge/ae423ad3-4135-46dd-b551-935a6caa974c)

**Comment by ericgribkoff** [comment]
I'm a little confused by the diff showing here, as https://github.com/GoogleCloudPlatform/traffic-director-grpc-examples/pull/21 has already been merged (which fixed local builds for me, but is still failing on CI at master, as you noted - trying to figure out why now)

**Comment by ericgribkoff** [comment]
The error we're seeing on master _may_ be due to an old gcc version; I sent you cl/369140857 to bump the Kokoro worker we're using for builds on this repo to match master on grpc/grpc.

**Comment by lidizheng** [comment]
This PR didn't fix the issue for me. One of the major goal is upgrading Bazel, which #21 has already done it. Closing the PR.

**Pull request closed without merging**
