### PR TITLE
java/wallet: create Dockerfile and also update dependency to 1.41.0

### PR DESCRIPTION
**Pull request by sanjaypujare**
- created Dockerfile to create an image for Java Wallet example
- Make Wallet dependent on 1.41.0 now that 1.41.0 is out

### CODE REVIEW

**Review by easwars — COMMENTED** [review]
Do you have an idea of the size of your docker image? You can find the `virtual size` on pantheon. The Go image is 50.4 MB.

**Comment by sanjaypujare** [comment]
> Do you have an idea of the size of your docker image? You can find the `virtual size` on pantheon. The Go image is 50.4 MB.

354.2 MB

**Review by dapengzhang0 — APPROVED** [review]
LGTM

**Comment by sanjaypujare** [comment]
@easwars are you okay with the changes in this PR?

**Comment by easwars** [comment]
> > Do you have an idea of the size of your docker image? You can find the `virtual size` on pantheon. The Go image is 50.4 MB.
> 
> 354.2 MB. Is the size going to cause any problem?

If it is possible to easily reduce the size, then we should do it. You can look at the Go `Dockerfile` where I only copy the binaries on to the final image. It would be nice if the image that we ask users to download and use is as small as reasonably possible.

**Comment by easwars** [comment]
> @easwars are you okay with the changes in this PR?

I'm mostly OK with the changes, except the size issue which I commented about on the other thread.

**Comment by sanjaypujare** [comment]
Unfortunately the base image we use - openjdk11 - itself takes 283 MB (as opposed to openjdk:8-jre-alpine  which is 84 MB). And our own stuff is around 50MB and that cannot be reduced (also is not worthwhile). Once we change our base image we can reduce the image size

**Pull request merged**
